# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaAdministracion.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ventanaHabitaciones import ventanaHabitaciones
from ventanaListaUsuarios import ventanaListaUsuarios



class ventanaAdministracion(object):
        def __init__(self, parent=None):
                self.parent = parent
        def setupUi(self, Administracion):
                Administracion.setObjectName("Administracion")
                Administracion.resize(802, 602)
                Administracion.setMinimumSize(QtCore.QSize(802, 602))
                Administracion.setMaximumSize(QtCore.QSize(802, 602))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(22)
                Administracion.setFont(font)
                Administracion.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("Recursos/HotelMascota.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                Administracion.setWindowIcon(icon)
                Administracion.setToolTip("")
                Administracion.setWhatsThis("")
                Administracion.setAccessibleName("")
                Administracion.setAccessibleDescription("")
                Administracion.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.centralwidget = QtWidgets.QWidget(Administracion)
                self.centralwidget.setObjectName("centralwidget")

                self.labelTitulo = QtWidgets.QLabel(self.centralwidget)
                self.labelTitulo.setGeometry(QtCore.QRect(-20, 0, 831, 81))
                font = QtGui.QFont()
                font.setPointSize(27)
                font.setBold(False)
                font.setWeight(50)
                self.labelTitulo.setFont(font)
                self.labelTitulo.setStyleSheet("background-color: rgb(79, 163, 166);")
                self.labelTitulo.setAlignment(QtCore.Qt.AlignCenter)
                self.labelTitulo.setObjectName("labelTitulo")

                #Boton gestion de habitacion
                self.BtnGestionDeHabitacion = QtWidgets.QPushButton(self.centralwidget)
                self.BtnGestionDeHabitacion.setGeometry(QtCore.QRect(90, 217, 271, 61))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(14)
                self.BtnGestionDeHabitacion.setFont(font)
                self.BtnGestionDeHabitacion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.BtnGestionDeHabitacion.setStyleSheet("background-color: rgb(79, 163, 166);\n"
        "border-radius: 10px;")
                self.BtnGestionDeHabitacion.setObjectName("BtnGestionDeHabitacion")

                #Accion boton gestion de habitacion
                self.BtnGestionDeHabitacion.clicked.connect(lambda:self.cambiar_ventana(ventanaHabitaciones))

                #Boton administracion de usuarios
                self.BtnAdministracionDeUsuarios = QtWidgets.QPushButton(self.centralwidget)
                self.BtnAdministracionDeUsuarios.setGeometry(QtCore.QRect(91, 370, 271, 61))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(14)
                self.BtnAdministracionDeUsuarios.setFont(font)
                self.BtnAdministracionDeUsuarios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.BtnAdministracionDeUsuarios.setStyleSheet("background-color: rgb(79, 163, 166);\n" "border-radius: 10px;\n")
                self.BtnAdministracionDeUsuarios.setObjectName("BtnAdministracionDeUsuarios")
                
                #Accion boton administracion de usuarios
                self.BtnAdministracionDeUsuarios.clicked.connect(lambda:self.cambiar_ventana(ventanaListaUsuarios))

                #Imagen del perrito
                self.labelFotoPerrito = QtWidgets.QLabel(self.centralwidget)
                self.labelFotoPerrito.setGeometry(QtCore.QRect(419, 142, 371, 321))
                self.labelFotoPerrito.setText("")
                self.labelFotoPerrito.setPixmap(QtGui.QPixmap("Recursos/FotoPerrito.png"))
                self.labelFotoPerrito.setScaledContents(True)
                self.labelFotoPerrito.setObjectName("labelFotoPerrito")

                #Boton atras
                self.BtnAtras = QtWidgets.QPushButton(self.centralwidget)
                self.BtnAtras.setGeometry(QtCore.QRect(20, 15, 51, 51))
                self.BtnAtras.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.BtnAtras.setStyleSheet("background-color: rgb(79, 163, 166);\n"
        "border-radius: 10px;")
                self.BtnAtras.setText("")
                icon1 = QtGui.QIcon()
                icon1.addPixmap(QtGui.QPixmap("Recursos/FotoBtnAtras.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.BtnAtras.setIcon(icon1)
                self.BtnAtras.setIconSize(QtCore.QSize(50, 50))
                self.BtnAtras.setObjectName("BtnAtras")
                
                #Accion boton atras
                self.BtnAtras.clicked.connect(self.cambiar_a_ventana_anterior)

                Administracion.setCentralWidget(self.centralwidget)

                self.retranslateUi(Administracion)
                QtCore.QMetaObject.connectSlotsByName(Administracion)

        def retranslateUi(self, Administracion):
                _translate = QtCore.QCoreApplication.translate
                Administracion.setWindowTitle(_translate("Administracion", "Hotel"))
                self.labelTitulo.setText(_translate("Administracion", "Administración"))
                self.BtnGestionDeHabitacion.setText(_translate("Administracion", "Gestion de habitacion"))
                self.BtnAdministracionDeUsuarios.setText(_translate("Administracion", "Administración de usuarios"))
        


        def cambiar_ventana(self, nombreVentana):
                self.uiVentanaActual = QtWidgets.QApplication.activeWindow()
                self.uiVentanaActual.close()
                self.nuevaVentana = QtWidgets.QMainWindow()
                self.ui = nombreVentana()
                self.ui.setupUi(self.nuevaVentana)
                self.nuevaVentana.show()

        
        def cambiar_a_ventana_anterior(self):
                self.ventanaActual = QtWidgets.QApplication.activeWindow()
                self.ventanaActual.close()

                from ventanaLogin import ventanaLogin  # Importación local para evitar el ciclo de importación
                self.ventanaAnterior = QtWidgets.QMainWindow(self.ventanaActual.parent())
                self.uiVentanaAnterior = ventanaLogin()
                self.uiVentanaAnterior.setupUi(self.ventanaAnterior)
                self.ventanaAnterior.show()






