# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaNuevaMascota.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import csv
from PyQt5 import QtCore, QtGui, QtWidgets


class ventanaNuevaMascota(object):
        def __init__(self, id_cliente, idHabitacion):
                self.id_cliente= id_cliente
                self.idHabitacion= idHabitacion
        def setupUi(self, NuevaMascota):
                NuevaMascota.setObjectName("NuevaMascota")
                NuevaMascota.resize(802, 602)
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("Recursos/HotelMascota.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                NuevaMascota.setWindowIcon(icon)
                self.centralwidget = QtWidgets.QWidget(NuevaMascota)
                self.centralwidget.setObjectName("centralwidget")
                self.labelTitulo = QtWidgets.QLabel(self.centralwidget)
                self.labelTitulo.setGeometry(QtCore.QRect(-20, 0, 831, 81))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(27)
                font.setBold(False)
                font.setWeight(50)
                self.labelTitulo.setFont(font)
                self.labelTitulo.setStyleSheet("background-color: rgb(79, 163, 166);")
                self.labelTitulo.setAlignment(QtCore.Qt.AlignCenter)
                self.labelTitulo.setObjectName("labelTitulo")

                #Boton atras
                self.BtnAtras = QtWidgets.QPushButton(self.centralwidget)
                self.BtnAtras.setGeometry(QtCore.QRect(20, 15, 51, 51))
                self.BtnAtras.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.BtnAtras.setStyleSheet("background-color: rgb(79, 163, 166);\n"
        "border-radius: 10px;")
                self.BtnAtras.setText("")
                icon1 = QtGui.QIcon()
                icon1.addPixmap(QtGui.QPixmap("Recursos/FotoBtnAtras.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.BtnAtras.setIcon(icon1)
                self.BtnAtras.setIconSize(QtCore.QSize(50, 50))
                self.BtnAtras.setObjectName("BtnAtras")

                #Accion boton atras
                self.BtnAtras.clicked.connect(self.cambiar_a_ventana_anterior)

                self.labelDatosNuevaMascota = QtWidgets.QLabel(self.centralwidget)
                self.labelDatosNuevaMascota.setGeometry(QtCore.QRect(40, 130, 381, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(13)
                self.labelDatosNuevaMascota.setFont(font)
                self.labelDatosNuevaMascota.setStyleSheet("background-color: rgb(79, 163, 166);\n"
        "border-radius: 18%;")
                self.labelDatosNuevaMascota.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
                self.labelDatosNuevaMascota.setIndent(29)
                self.labelDatosNuevaMascota.setObjectName("labelDatosNuevaMascota")
                self.labelIconFlechaAbajo = QtWidgets.QLabel(self.centralwidget)
                self.labelIconFlechaAbajo.setGeometry(QtCore.QRect(359, 136, 31, 31))
                self.labelIconFlechaAbajo.setText("")
                self.labelIconFlechaAbajo.setPixmap(QtGui.QPixmap("Recursos/IconFlechaAbajo.png"))
                self.labelIconFlechaAbajo.setScaledContents(True)
                self.labelIconFlechaAbajo.setObjectName("labelIconFlechaAbajo")
                self.labelFotoPerrito = QtWidgets.QLabel(self.centralwidget)
                self.labelFotoPerrito.setGeometry(QtCore.QRect(507, 191, 281, 271))
                self.labelFotoPerrito.setText("")
                self.labelFotoPerrito.setPixmap(QtGui.QPixmap("Recursos/FotoPerrito.png"))
                self.labelFotoPerrito.setScaledContents(True)
                self.labelFotoPerrito.setObjectName("labelFotoPerrito")
                self.labelNombre = QtWidgets.QLabel(self.centralwidget)
                self.labelNombre.setGeometry(QtCore.QRect(35, 200, 101, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                self.labelNombre.setFont(font)
                self.labelNombre.setAlignment(QtCore.Qt.AlignCenter)
                self.labelNombre.setObjectName("labelNombre")
                self.inputNombre = QtWidgets.QLineEdit(self.centralwidget)
                self.inputNombre.setGeometry(QtCore.QRect(50, 240, 151, 31))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(10)
                self.inputNombre.setFont(font)
                self.inputNombre.setText("")
                self.inputNombre.setObjectName("inputNombre")
                self.labelEspecie = QtWidgets.QLabel(self.centralwidget)
                self.labelEspecie.setGeometry(QtCore.QRect(254, 200, 101, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                self.labelEspecie.setFont(font)
                self.labelEspecie.setAlignment(QtCore.Qt.AlignCenter)
                self.labelEspecie.setObjectName("labelEspecie")
                self.inputRaza = QtWidgets.QLineEdit(self.centralwidget)
                self.inputRaza.setGeometry(QtCore.QRect(50, 320, 151, 31))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(10)
                self.inputRaza.setFont(font)
                self.inputRaza.setText("")
                self.inputRaza.setObjectName("inputRaza")
                self.labelRaza = QtWidgets.QLabel(self.centralwidget)
                self.labelRaza.setGeometry(QtCore.QRect(51, 280, 51, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                self.labelRaza.setFont(font)
                self.labelRaza.setAlignment(QtCore.Qt.AlignCenter)
                self.labelRaza.setObjectName("labelRaza")
                self.labelFechaNacimiento = QtWidgets.QLabel(self.centralwidget)
                self.labelFechaNacimiento.setGeometry(QtCore.QRect(53, 360, 151, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                self.labelFechaNacimiento.setFont(font)
                self.labelFechaNacimiento.setAlignment(QtCore.Qt.AlignCenter)
                self.labelFechaNacimiento.setObjectName("labelFechaNacimiento")
                self.dateEditFechaNacimiento = QtWidgets.QDateEdit(self.centralwidget)
                self.dateEditFechaNacimiento.setGeometry(QtCore.QRect(50, 400, 151, 31))
                self.dateEditFechaNacimiento.setObjectName("dateEditFechaNacimiento")
                self.labelPeso = QtWidgets.QLabel(self.centralwidget)
                self.labelPeso.setGeometry(QtCore.QRect(266, 451, 41, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                self.labelPeso.setFont(font)
                self.labelPeso.setAlignment(QtCore.Qt.AlignCenter)
                self.labelPeso.setObjectName("labelPeso")
                self.inputPeso = QtWidgets.QLineEdit(self.centralwidget)
                self.inputPeso.setGeometry(QtCore.QRect(309, 456, 31, 31))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(10)
                self.inputPeso.setFont(font)
                self.inputPeso.setText("")
                self.inputPeso.setObjectName("inputPeso")
                self.labelSize = QtWidgets.QLabel(self.centralwidget)
                self.labelSize.setGeometry(QtCore.QRect(268, 360, 71, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                self.labelSize.setFont(font)
                self.labelSize.setAlignment(QtCore.Qt.AlignCenter)
                self.labelSize.setObjectName("labelSize")
                self.labelSexo = QtWidgets.QLabel(self.centralwidget)
                self.labelSexo.setGeometry(QtCore.QRect(268, 281, 71, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                self.labelSexo.setFont(font)
                self.labelSexo.setAlignment(QtCore.Qt.AlignCenter)
                self.labelSexo.setObjectName("labelSexo")
                self.comboBoxSexo = QtWidgets.QComboBox(self.centralwidget)
                self.comboBoxSexo.setGeometry(QtCore.QRect(270, 320, 81, 31))
                self.comboBoxSexo.setObjectName("comboBoxSexo")
                self.comboBoxSexo.addItem("")
                self.comboBoxSexo.addItem("")
                self.comboBoxSexo.addItem("")

                #Boton Agregar Mascotas
                self.BtnAgregarMascota = QtWidgets.QPushButton(self.centralwidget)
                self.BtnAgregarMascota.setGeometry(QtCore.QRect(638, 545, 151, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                font.setBold(True)
                font.setWeight(75)
                self.BtnAgregarMascota.setFont(font)
                self.BtnAgregarMascota.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.BtnAgregarMascota.setStyleSheet("background-color: rgb(79, 163, 166);\n"
        "border-radius:15px;")
                self.BtnAgregarMascota.setObjectName("BtnAgregarMascota")

                #Accion Boton Agregar Mascota
                self.BtnAgregarMascota.clicked.connect(self.agregar_mascota)

                self.comboBoxSize = QtWidgets.QComboBox(self.centralwidget)
                self.comboBoxSize.setGeometry(QtCore.QRect(270, 400, 81, 31))
                self.comboBoxSize.setObjectName("comboBoxSize")
                self.comboBoxSize.addItem("")
                self.comboBoxSize.addItem("")
                self.comboBoxSize.addItem("")
                self.comboBoxSize.addItem("")
                self.comboBoxSize.addItem("")
                self.comboBoxSize.addItem("")
                self.labelKg = QtWidgets.QLabel(self.centralwidget)
                self.labelKg.setGeometry(QtCore.QRect(336, 452, 41, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                self.labelKg.setFont(font)
                self.labelKg.setAlignment(QtCore.Qt.AlignCenter)
                self.labelKg.setObjectName("labelKg")
                self.comboBoxEspecie = QtWidgets.QComboBox(self.centralwidget)
                self.comboBoxEspecie.setGeometry(QtCore.QRect(270, 240, 81, 31))
                self.comboBoxEspecie.setObjectName("comboBoxEspecie")
                self.comboBoxEspecie.addItem("")
                self.comboBoxEspecie.addItem("")
                self.comboBoxEspecie.addItem("")
                self.comboBoxEspecie.addItem("")
                self.comboBoxEspecie.addItem("")
                NuevaMascota.setCentralWidget(self.centralwidget)

                self.retranslateUi(NuevaMascota)
                QtCore.QMetaObject.connectSlotsByName(NuevaMascota)

                self.inputNombre.textChanged.connect(self.actualizar_estado_boton)
                self.comboBoxEspecie.currentIndexChanged.connect(self.actualizar_estado_boton)
                self.inputRaza.textChanged.connect(self.actualizar_estado_boton)
                self.comboBoxSexo.currentIndexChanged.connect(self.actualizar_estado_boton)
                self.comboBoxSize.currentIndexChanged.connect(self.actualizar_estado_boton)
                self.inputPeso.textChanged.connect(self.actualizar_estado_boton)

        def retranslateUi(self, NuevaMascota):
                _translate = QtCore.QCoreApplication.translate
                NuevaMascota.setWindowTitle(_translate("NuevaMascota", "Hotel"))
                self.labelTitulo.setText(_translate("NuevaMascota", "Datos Mascota"))
                self.labelDatosNuevaMascota.setText(_translate("NuevaMascota", "Datos del nueva mascota"))
                self.labelNombre.setText(_translate("NuevaMascota", "Nombre"))
                self.labelEspecie.setText(_translate("NuevaMascota", "Especie"))
                self.labelRaza.setText(_translate("NuevaMascota", "Raza"))
                self.labelFechaNacimiento.setText(_translate("NuevaMascota", "Fecha de Nacimiento"))
                self.labelPeso.setText(_translate("NuevaMascota", "Peso"))
                self.labelSize.setText(_translate("NuevaMascota", "Tamaño"))
                self.labelSexo.setText(_translate("NuevaMascota", "Sexo"))
                self.comboBoxSexo.setItemText(0, _translate("NuevaMascota", "Elegir"))
                self.comboBoxSexo.setItemText(1, _translate("NuevaMascota", "Hembra"))
                self.comboBoxSexo.setItemText(2, _translate("NuevaMascota", "Macho"))
                self.BtnAgregarMascota.setText(_translate("NuevaMascota", "Agregar Mascota"))
                self.comboBoxSize.setItemText(0, _translate("NuevaMascota", "Elegir"))
                self.comboBoxSize.setItemText(1, _translate("NuevaMascota", "Muy Pequeño"))
                self.comboBoxSize.setItemText(2, _translate("NuevaMascota", "Pequeño"))
                self.comboBoxSize.setItemText(3, _translate("NuevaMascota", "Mediano"))
                self.comboBoxSize.setItemText(4, _translate("NuevaMascota", "Grande"))
                self.comboBoxSize.setItemText(5, _translate("NuevaMascota", "Muy Grande"))
                self.labelKg.setText(_translate("NuevaMascota", "kg"))
                self.comboBoxEspecie.setItemText(0, _translate("NuevaMascota", "Elegir"))
                self.comboBoxEspecie.setItemText(1, _translate("NuevaMascota", "Perro"))
                self.comboBoxEspecie.setItemText(2, _translate("NuevaMascota", "Gato"))
                self.comboBoxEspecie.setItemText(3, _translate("NuevaMascota", "Roedor"))
                self.comboBoxEspecie.setItemText(4, _translate("NuevaMascota", "Otro"))

        def cambiar_a_ventana_anterior(self):
                self.ventanaActual = QtWidgets.QApplication.activeWindow()
                self.ventanaActual.close()

                from ventanaListaMascota import ventanaListaMascotas  # Importación local para evitar el ciclo de importación
                self.ventanaAnterior = QtWidgets.QMainWindow(self.ventanaActual.parent())
                self.uiVentanaAnterior = ventanaListaMascotas(self.id_cliente,self.idHabitacion)
                self.uiVentanaAnterior.setupUi(self.ventanaAnterior)
                self.ventanaAnterior.show()

        def verificar_campos_llenos(self):
                campos_llenos = all([
                        self.inputNombre.text(),
                        self.comboBoxEspecie.currentIndex() != 0,
                        self.inputRaza.text(),
                        self.dateEditFechaNacimiento.date().isValid(),
                        self.comboBoxSexo.currentIndex() != 0,
                        self.comboBoxSize.currentIndex() != 0,
                        self.inputPeso.text(),

                ])
                return campos_llenos
        
        def actualizar_estado_boton(self):
                self.BtnAgregarMascota.setEnabled(self.verificar_campos_llenos())
        
        def agregar_mascota(self):
                idmascota= self.id_cliente
                nombre = self.inputNombre.text()
                especie = self.comboBoxEspecie.currentText()
                raza = self.inputRaza.text()
                fecha_nacimiento = self.dateEditFechaNacimiento.date().toString("dd-MM-yyyy")
                sexo = self.comboBoxSexo.currentText()
                size = self.comboBoxSize.currentText()
                peso = self.inputPeso.text()

                
                # Crear una lista con los datos del nuevo mascota
                nueva_mascota = [idmascota, nombre, especie , raza , fecha_nacimiento, sexo, size, peso]
                
                # Abrir el archivo CSV en modo de escritura (append)
                with open('ArchivosCSV/Mascotas.csv', 'a', newline='') as file:
                        writer = csv.writer(file)
                
                        # Escribir los datos del nuevo mascota en una nueva fila del archivo CSV
                        writer.writerow(nueva_mascota)
                
                # Mostrar mensaje de éxito
                #QtWidgets.QMessageBox.information(self, "Éxito", "El mascota ha sido agregado correctamente.")
                
                # Limpiar los campos de entrada
                self.inputNombre.setText("")
                self.comboBoxEspecie.setCurrentIndex(0)
                self.inputRaza.setText("")
                self.dateEditFechaNacimiento.setDate(QtCore.QDate.currentDate())
                self.comboBoxSexo.setCurrentIndex(0)
                self.comboBoxSize.setCurrentIndex(0)
                self.inputPeso.setText("")

                # Mostrar un mensaje de éxito al mascota
                QtWidgets.QMessageBox.information(self.centralwidget, "Éxito", "El mascota fue ingresado correctamente.")

                self.cambiar_a_ventana_anterior()