# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaEditarCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import csv
from PyQt5 import QtCore, QtGui, QtWidgets


class ventanaEditarCliente(object):
        def __init__(self, cont, id_cliente, idHabitacion):
                self.cont = cont
                self.id_cliente= id_cliente
                self.idHabitacion= idHabitacion
        def setupUi(self, EditarCliente):
                EditarCliente.setObjectName("EditarCliente")
                EditarCliente.resize(802, 602)
                EditarCliente.setMinimumSize(802, 602)
                EditarCliente.setMaximumSize(802, 602)
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("Recursos/HotelMascota.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                EditarCliente.setWindowIcon(icon)
                self.centralwidget = QtWidgets.QWidget(EditarCliente)
                self.centralwidget.setObjectName("centralwidget")
                self.labelTitulo = QtWidgets.QLabel(self.centralwidget)
                self.labelTitulo.setGeometry(QtCore.QRect(-20, 0, 831, 81))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(27)
                font.setBold(False)
                font.setWeight(50)
                self.labelTitulo.setFont(font)
                self.labelTitulo.setStyleSheet("background-color: rgb(79, 163, 166);")
                self.labelTitulo.setAlignment(QtCore.Qt.AlignCenter)
                self.labelTitulo.setObjectName("labelTitulo")

                #Boton Atras
                self.BtnAtras = QtWidgets.QPushButton(self.centralwidget)
                self.BtnAtras.setGeometry(QtCore.QRect(20, 15, 51, 51))
                self.BtnAtras.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.BtnAtras.setStyleSheet("QPushButton {\n"
"  \n"
"    \n"
"    background-color: rgba(0,0,0,0);\n"
"    border-radius: 20px;\n"
"\n"
"  \n"
"}\n"
"\n"
"\n"
"QPushButton::hover {\n"
"    background: #74b6b6;\n"
"}\n"
"")
                self.BtnAtras.setText("")
                icon1 = QtGui.QIcon()
                icon1.addPixmap(QtGui.QPixmap("Recursos/FotoBtnAtras.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.BtnAtras.setIcon(icon1)
                self.BtnAtras.setIconSize(QtCore.QSize(50, 50))
                self.BtnAtras.setObjectName("BtnAtras")

                #Accion boton atras
                self.BtnAtras.clicked.connect(self.cambiar_a_ventana_anterior)

                self.labelDatosNuevoClientes = QtWidgets.QLabel(self.centralwidget)
                self.labelDatosNuevoClientes.setGeometry(QtCore.QRect(40, 130, 381, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(13)
                self.labelDatosNuevoClientes.setFont(font)
                self.labelDatosNuevoClientes.setStyleSheet("background-color: rgb(79, 163, 166);\n"
        "border-radius: 18%;")
                self.labelDatosNuevoClientes.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
                self.labelDatosNuevoClientes.setIndent(29)
                self.labelDatosNuevoClientes.setObjectName("labelDatosNuevoClientes")
                self.labelIconFlechaAbajo = QtWidgets.QLabel(self.centralwidget)
                self.labelIconFlechaAbajo.setGeometry(QtCore.QRect(359, 136, 31, 31))
                self.labelIconFlechaAbajo.setText("")
                self.labelIconFlechaAbajo.setPixmap(QtGui.QPixmap("Recursos/IconFlechaAbajo.png"))
                self.labelIconFlechaAbajo.setScaledContents(True)
                self.labelIconFlechaAbajo.setObjectName("labelIconFlechaAbajo")
                self.labelFotoPerrito = QtWidgets.QLabel(self.centralwidget)
                self.labelFotoPerrito.setGeometry(QtCore.QRect(507, 191, 281, 271))
                self.labelFotoPerrito.setText("")
                self.labelFotoPerrito.setPixmap(QtGui.QPixmap("Recursos/FotoPerrito.png"))
                self.labelFotoPerrito.setScaledContents(True)
                self.labelFotoPerrito.setObjectName("labelFotoPerrito")
                self.labelNombre = QtWidgets.QLabel(self.centralwidget)
                self.labelNombre.setGeometry(QtCore.QRect(35, 200, 101, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                self.labelNombre.setFont(font)
                self.labelNombre.setAlignment(QtCore.Qt.AlignCenter)
                self.labelNombre.setObjectName("labelNombre")
                self.inputNombre = QtWidgets.QLineEdit(self.centralwidget)
                self.inputNombre.setGeometry(QtCore.QRect(50, 240, 151, 31))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(10)
                self.inputNombre.setFont(font)
                self.inputNombre.setText("")
                self.inputNombre.setObjectName("inputNombre")
                self.labelApellido = QtWidgets.QLabel(self.centralwidget)
                self.labelApellido.setGeometry(QtCore.QRect(244, 200, 101, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                self.labelApellido.setFont(font)
                self.labelApellido.setAlignment(QtCore.Qt.AlignCenter)
                self.labelApellido.setObjectName("labelApellido")
                self.inputApellido = QtWidgets.QLineEdit(self.centralwidget)
                self.inputApellido.setGeometry(QtCore.QRect(260, 240, 151, 31))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(10)
                self.inputApellido.setFont(font)
                self.inputApellido.setText("")
                self.inputApellido.setObjectName("inputApellido")
                self.inputRut = QtWidgets.QLineEdit(self.centralwidget)
                self.inputRut.setEnabled(False)
                self.inputRut.setGeometry(QtCore.QRect(50, 320, 151, 31))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(10)
                self.inputRut.setFont(font)
                self.inputRut.setText("")
                self.inputRut.setObjectName("inputRut")
                self.labelRut = QtWidgets.QLabel(self.centralwidget)
                self.labelRut.setGeometry(QtCore.QRect(20, 280, 101, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                self.labelRut.setFont(font)
                self.labelRut.setAlignment(QtCore.Qt.AlignCenter)
                self.labelRut.setObjectName("labelRut")
                self.labelFechaNacimiento = QtWidgets.QLabel(self.centralwidget)
                self.labelFechaNacimiento.setGeometry(QtCore.QRect(53, 360, 151, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                self.labelFechaNacimiento.setFont(font)
                self.labelFechaNacimiento.setAlignment(QtCore.Qt.AlignCenter)
                self.labelFechaNacimiento.setObjectName("labelFechaNacimiento")
                self.dateEditFechaNacimiento = QtWidgets.QDateEdit(self.centralwidget)
                self.dateEditFechaNacimiento.setGeometry(QtCore.QRect(50, 400, 151, 31))
                self.dateEditFechaNacimiento.setObjectName("dateEditFechaNacimiento")
                self.inputCorreoElectronico = QtWidgets.QLineEdit(self.centralwidget)
                self.inputCorreoElectronico.setGeometry(QtCore.QRect(50, 479, 151, 31))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(10)
                self.inputCorreoElectronico.setFont(font)
                self.inputCorreoElectronico.setText("")
                self.inputCorreoElectronico.setObjectName("inputCorreoElectronico")
                self.labelCorreoElectronico = QtWidgets.QLabel(self.centralwidget)
                self.labelCorreoElectronico.setGeometry(QtCore.QRect(54, 439, 131, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                self.labelCorreoElectronico.setFont(font)
                self.labelCorreoElectronico.setAlignment(QtCore.Qt.AlignCenter)
                self.labelCorreoElectronico.setObjectName("labelCorreoElectronico")
                self.labelDomicilio = QtWidgets.QLabel(self.centralwidget)
                self.labelDomicilio.setGeometry(QtCore.QRect(234, 440, 131, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                self.labelDomicilio.setFont(font)
                self.labelDomicilio.setAlignment(QtCore.Qt.AlignCenter)
                self.labelDomicilio.setObjectName("labelDomicilio")
                self.inputDomicilio = QtWidgets.QLineEdit(self.centralwidget)
                self.inputDomicilio.setGeometry(QtCore.QRect(260, 480, 151, 31))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(10)
                self.inputDomicilio.setFont(font)
                self.inputDomicilio.setText("")
                self.inputDomicilio.setObjectName("inputDomicilio")


                self.labelTelefono = QtWidgets.QLabel(self.centralwidget)
                self.labelTelefono.setGeometry(QtCore.QRect(258, 360, 71, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                self.labelTelefono.setFont(font)
                self.labelTelefono.setAlignment(QtCore.Qt.AlignCenter)
                self.labelTelefono.setObjectName("labelTelefono")
                self.inputTelefono = QtWidgets.QLineEdit(self.centralwidget)
                self.inputTelefono.setGeometry(QtCore.QRect(260, 400, 151, 31))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(10)
                self.inputTelefono.setFont(font)
                self.inputTelefono.setText("")
                self.inputTelefono.setObjectName("inputTelefono")
                positive_validator = QtGui.QIntValidator(1, 999999999, self.inputTelefono)
                self.inputTelefono.setValidator(positive_validator)


                self.labelGenero = QtWidgets.QLabel(self.centralwidget)
                self.labelGenero.setGeometry(QtCore.QRect(258, 281, 71, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                self.labelGenero.setFont(font)
                self.labelGenero.setAlignment(QtCore.Qt.AlignCenter)
                self.labelGenero.setObjectName("labelGenero")
                self.comboBoxGenero = QtWidgets.QComboBox(self.centralwidget)
                self.comboBoxGenero.setGeometry(QtCore.QRect(260, 320, 81, 31))
                self.comboBoxGenero.setObjectName("comboBoxGenero")
                self.comboBoxGenero.addItem("")
                self.comboBoxGenero.addItem("")
                self.comboBoxGenero.addItem("")

                #Boton cliente editado
                self.BtnGuardarClienteEditado = QtWidgets.QPushButton(self.centralwidget)
                self.BtnGuardarClienteEditado.setGeometry(QtCore.QRect(639, 540, 151, 41))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(11)
                font.setBold(True)
                font.setWeight(75)
                self.BtnGuardarClienteEditado.setFont(font)
                self.BtnGuardarClienteEditado.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.BtnGuardarClienteEditado.setStyleSheet("background-color: rgb(79, 163, 166);\n"
        "border-radius:15px;")
                self.BtnGuardarClienteEditado.setObjectName("BtnGuardarClienteEditado")
                EditarCliente.setCentralWidget(self.centralwidget)

                #Accion boton guardar usuario editado
                self.BtnGuardarClienteEditado.clicked.connect(self.guardar_usuario_editado)

                self.retranslateUi(EditarCliente)
                QtCore.QMetaObject.connectSlotsByName(EditarCliente)

                self.obtener_datos_usuario()

        def retranslateUi(self, EditarCliente):
                _translate = QtCore.QCoreApplication.translate
                EditarCliente.setWindowTitle(_translate("EditarCliente", "Hotel"))
                self.labelTitulo.setText(_translate("EditarCliente", "Editar Cliente"))
                self.labelDatosNuevoClientes.setText(_translate("EditarCliente", "Datos del cliente a editar"))
                self.labelNombre.setText(_translate("EditarCliente", "Nombre"))
                self.labelApellido.setText(_translate("EditarCliente", "Apellido"))
                self.labelRut.setText(_translate("EditarCliente", "Rut"))
                self.labelFechaNacimiento.setText(_translate("EditarCliente", "Fecha de Nacimiento"))
                self.labelCorreoElectronico.setText(_translate("EditarCliente", "Correo electronico"))
                self.labelDomicilio.setText(_translate("EditarCliente", "Domicilio"))
                self.labelTelefono.setText(_translate("EditarCliente", "Teléfono"))
                self.labelGenero.setText(_translate("EditarCliente", "Género"))
                self.comboBoxGenero.setItemText(0, _translate("EditarCliente", "Elegir"))
                self.comboBoxGenero.setItemText(1, _translate("EditarCliente", "Femenino"))
                self.comboBoxGenero.setItemText(2, _translate("EditarCliente", "Masculino"))
                self.BtnGuardarClienteEditado.setText(_translate("EditarCliente", "Acetar"))


        def cambiarVentana(self, clase, cliente_id):
                self.uiVentanaActual = QtWidgets.QApplication.activeWindow()
                self.uiVentanaActual.close()
                self.nuevaVentana = QtWidgets.QMainWindow()
                self.ui = clase(cliente_id, self.idHabitacion)  # Pasa el idCliente y el idHabitacion como parámetros
                self.ui.setupUi(self.nuevaVentana)
                self.nuevaVentana.show()
        
        def cambiar_a_ventana_anterior(self):
                self.ventanaActual = QtWidgets.QApplication.activeWindow()
                self.ventanaActual.close()

                from ventanaListaClientes import ventanaListaCliente  # Importación local para evitar el ciclo de importación
                self.ventanaAnterior = QtWidgets.QMainWindow(self.ventanaActual.parent())
                self.uiVentanaAnterior = ventanaListaCliente(self.id_cliente,self.idHabitacion,self.cont)
                self.uiVentanaAnterior.setupUi(self.ventanaAnterior)
                self.ventanaAnterior.show()

        def obtener_datos_usuario(self):
        # Abrir y leer el archivo CSV
                with open('ArchivosCSV/Cliente.csv', 'r') as file:
                        reader = csv.reader(file)
                        next(reader)  # Saltar la primera línea si contiene encabezados

                        # Buscar el usuario correspondiente al usuario_id
                        for row in reader:
                                if row[0] == str(self.id_cliente):
                                        # Obtener los datos del usuario
                                        nombre = row[1]
                                        apellido = row[2]
                                        genero = row[3]
                                        fecha_nacimiento = row[4]
                                        rut = row[5]
                                        correo = row[6]
                                        telefono = row[7]
                                        domicilio = row[8]

                                        # Establecer los datos en los labels
                                        self.inputNombre.setText(nombre)
                                        self.inputApellido.setText(apellido)
                                        self.inputRut.setText(rut)
                                        # Establecer el valor de la fecha de nacimiento en el dateEdit
                                        self.dateEditFechaNacimiento.setDate(QtCore.QDate.fromString(fecha_nacimiento, "yyyy-MM-dd"))
                                        self.inputCorreoElectronico.setText(correo)
                                        self.inputDomicilio.setText(domicilio)
                                        self.inputTelefono.setText(telefono)

                                        # Establecer el valor del género en el comboBoxGenero
                                        if genero == "Femenino":
                                                self.comboBoxGenero.setCurrentIndex(1)
                                        elif genero == "Masculino":
                                                self.comboBoxGenero.setCurrentIndex(2)

                                        # Salir del bucle después de encontrar el usuario
                                        break
                
        def guardar_usuario_editado(self):
                nombre = self.inputNombre.text()
                apellido = self.inputApellido.text()
                rut = self.inputRut.text()
                fecha_nacimiento = self.dateEditFechaNacimiento.date().toString(QtCore.Qt.ISODate)
                correo = self.inputCorreoElectronico.text()
                domicilio = self.inputDomicilio.text()
                telefono = self.inputTelefono.text()
                genero = self.comboBoxGenero.currentText()


                # Aquí puedes realizar la actualización de los datos del usuario en el archivo CSV
                # Por ejemplo, puedes abrir el archivo CSV, leer los datos, actualizar los datos del usuario específico
                # y luego guardar los cambios en el archivo

                with open('ArchivosCSV/Cliente.csv', 'r') as archivo_csv:
                        # Leer los datos del archivo CSV
                        csv_reader = csv.reader(archivo_csv)
                        lineas = list(csv_reader)

                        # Encontrar la línea correspondiente al usuario_id
                        for i, linea in enumerate(lineas):
                                if linea[0] == self.id_cliente:
                                        # Actualizar los datos en la línea correspondiente
                                        lineas[i] = [self.id_cliente, nombre, apellido, genero, fecha_nacimiento, rut, correo, telefono, domicilio]
                                        break

                # Guardar los cambios en el archivo CSV
                with open('ArchivosCSV/Cliente.csv', 'w', newline='') as archivo_csv:
                        csv_writer = csv.writer(archivo_csv)
                        csv_writer.writerows(lineas)

                # Mostrar un mensaje de éxito al usuario
                QtWidgets.QMessageBox.information(self.centralwidget, "Éxito", "Los datos del usuario han sido actualizados correctamente.")

                self.cambiar_a_ventana_anterior()
